version: '3'
services:
  app:
    build:
      context: ./containers/rails
      args:
        RUBY_VERSION: ${RUBY_VERSION}
        APP_NAME: ${APP_NAME}
    env_file:
      - ./db.env
    command: bundle exec puma -C /${APP_NAME}/config/puma.rb
    volumes:
      - .:/${APP_NAME}
      - public-data:/${APP_NAME}/public
      - tmp-data:/${APP_NAME}/tmp
      - log-data:/${APP_NAME}/log
      - bundle:/usr/local/bundle
    depends_on:
      - db
  web:
    build:
      context: ./containers/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        APP_NAME: ${APP_NAME}
    volumes:
      - public-data:/${APP_NAME}/public
      - tmp-data:/${APP_NAME}/tmp
    ports:
      - 80:80
    depends_on:
      - app
  db:
    build:
      context: ./containers/mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    env_file:
      - ./db.env
    ports:
      - ${MYSQL_PORT}
    volumes:
      - db-data:/var/lib/mysql
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
  bundle: